# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Gitea installation tasks
  when: gitea_enabled | bool
  tags:
    - setup-all
    - setup-gitea
    - install-all
    - install-gitea
  block:
    - name: Validate Gitea configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Gitea
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Gitea uninstallation tasks
  when: not gitea_enabled | bool
  tags:
    - setup-all
    - setup-gitea
  block:
    - name: Uninstall Gitea
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
