# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "gitea_config_database_type", "new": "gitea_database_type" }
    - { "old": "gitea_config_database_hostname", "new": "gitea_database_hostname" }
    - { "old": "gitea_config_database_port", "new": "gitea_database_port" }
    - { "old": "gitea_config_database_name", "new": "gitea_database_name" }
    - { "old": "gitea_config_database_username", "new": "gitea_database_username" }
    - { "old": "gitea_config_database_password", "new": "gitea_database_password" }
    - { "old": "gitea_container_additional_environment_variables", "new": "gitea_environment_variables_additional_variables" }

- name: Fail if required Gitea settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`) for using this role.
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - { "name": "gitea_hostname", when: true }
    - { "name": "gitea_uid", when: true }
    - { "name": "gitea_gid", when: true }
    - { "name": "gitea_database_hostname", when: true }
    - { "name": "gitea_database_username", when: true }
    - { "name": "gitea_database_password", when: true }
    - { "name": "gitea_container_labels_traefik_compression_middleware_name", when: "{{ gitea_container_labels_traefik_compression_middleware_enabled }}" }

- name: Run if Traefik is enabled
  when: gitea_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Gitea are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - gitea_container_labels_traefik_hostname
        - gitea_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `gitea_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if gitea_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          gitea_container_labels_traefik_path_prefix (`{{ gitea_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/gitea`).
      when: "gitea_container_labels_traefik_path_prefix != '/' and gitea_container_labels_traefik_path_prefix[-1] == '/'"
